name: run-test

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.mvn/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '**/.mvn/wrapper/maven-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Configure Maven settings
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          echo '<settings> <servers> <server> <id>github</id> <username>'$GIT_USERNAME'</username> <password>'$GIT_TOKEN'</password> </server> </servers> </settings>' > settings.xml
          ls -lh settings.xml

      - name: Build with Maven (local)
        run: mvn deploy -s settings.xml
